### ISSUE TITLE
Something appears to be broken.

### ISSUE THREAD

**Issue by soarn** [sixem/eyy-indexer#1]
Context:
content directory: `/var/www/html/`
src directory: `/var/www/src/`
public directory: `/var/www/html/public/`
all of my content is located in `/var/ww/html/*` (not in `/var/www/html/public/*` folder)
apache2 location: `/etc/apache2/`
server location: [`s.soarn.pro`](https://s.soarn.pro)

---

I have in `/etc/apache2/sites-avaiable` a file named `s.soarn.pro.conf` and is has:
```conf
<VirtualHost *:80>
    ServerName https://s.soarn.pro/
    ServerAlias www.s.soarn.pro/

    DocumentRoot "/var/www/website/"
    DirectoryIndex index.php index.html index.htm /indexer.php
</VirtualHost>
```
I also have in `/etc/apache2/` a `.htaccess` file with
```htaccess
DirectoryIndex index.php index.html index.htm /indexer.php
```
In the `/etc/apache2/` is the `apache2.conf` file, which should be the default file, I added to the end of it:
```conf
irectoryIndex index.php index.html index.htm /indexer.php
# Requires rewrite module to be enabled (sudo a2enmod rewrite).
RewriteEngine On
RewriteRule ^/indexer.php(.*)$ - [R=404,L]
```
So far, even with `systemctl restart apache2` nothing is working, and I just get the default apache2 layout on the server.  I also installed `mbstring`, `jquery.scrollTo`, and `Tocca.js`.  However nothing appears to be working.  Is there something that I am doing wrong?

Thanks, Soarn.

**Comment by sixem** [comment]
From what i can see you have placed the `public` directory in your `DocumentRoot`. Try moving the files from `public` straight into your `DocumentRoot` directory instead, and then edit the `indexer.php` to make sure it points directly to the source file, this line right here: `require_once('../src/eyy-indexer.php');`.

Alternatively, you might (don't know too much about apache) be able to do `DirectoryIndex index.php index.html index.htm /public/indexer.php` instead, but you'd still have to edit the `indexer.php` to make sure it finds the source file, because by default it just looks for a `src` folder below its location.

The default directory setup is just a recommendation, so some tweaking might be needed if you are not running a configuration where `DocumentRoot` points directly to the `public` folder with a `src` folder directly below that again.

If it still doesn't work, then i'll have to test it out for myself.

**Comment by soarn** [comment]
Well jeez, why didn't I realize that?  But thank you so much!  This has 100% fixed it, thank you a lot!
