### ISSUE TITLE
Invalid path. path does not exist

### ISSUE THREAD

**Issue by prtst33** [sixem/eyy-indexer#19]
How can I solve this? Thanks

Error:

Exception: invalid path. path does not exist. in /var/www/html/xxx/indexer.php:276 Stack trace: #0 /var/www/html/xxx/indexer.php(726): Indexer->__construct('/xxx/indexer....', Array) #1 {main} (4)

Fatal error - Exiting.

**Comment by sixem** [comment]
Hmm, is the `.php` file placed in the www root or in a subdirectory below that? It looks like it is in a subdirectory to me, but I could be wrong. Is `/var/www/html/xxx/` the root directory in this case, or is it `/var/www/html/`?

**Comment by prtst33** [comment]
/var/www/html/ is the root directory

**Comment by sixem** [comment]
Ok, but the `.php` file is placed here `/var/www/html/xxx/indexer.php`? If so, that's the problem, it has to be in the root directory.

**Comment by prtst33** [comment]
It works. Thanks.
Is it hard to modify to make it work in a subdirectory?

**Comment by sixem** [comment]
Did you follow the setup [here](https://github.com/sixem/eyy-indexer#2-server-configuration) for your web server by setting the default indexes? By doing that, you should be able to browse all the directories within your www root, like `/var/www/html/xxx/` and so on while having the file in your root directory.

If you really need to place the `.php` file somewhere else, then you can see [this](https://github.com/sixem/eyy-indexer/blob/master/CONFIG.md#server) link `(under advanced -> server)`, it'll show you pass the root path to the script directly so that the indexer can work from somewhere else, but using that method really shouldn't be necessary in most cases.

**Comment by prtst33** [comment]
Perfect. Thanks.

**Comment by sixem** [comment]
Sounds like you solved it then 😄 

Don't be afraid to ask if you have any other questions or problems.
