### ISSUE TITLE
Updating from an old release.

### ISSUE THREAD

**Issue by soarn** [sixem/eyy-indexer#8]
Hello!  It is me, the person from #1 and #2, I was wondering what the easiest way to go about updating the indexer is.  I've been using it for a long time and I'm running version 1.0.4.  So what is the best way for me to update my files without losing any of my configuration data?  Its probably as simple as just dragging and dropping everything into the other stuff, minus the config file, but I just wanted to double check.

Thanks.

**Comment by sixem** [comment]
I've removed the configuration file in the newer versions, so that file will no longer have any effect and can be removed if upgrading. Instead, the configuration can now be set by editing the `indexer.php` directly, there's an array the top of the file which can be customized.

To update i would have a look at the [configuration](https://github.com/sixem/eyy-indexer/blob/master/CONFIG.md) page and attempt to transfer whatever old settings you have to the new format.

**Comment by soarn** [comment]
Excellent!  Thank you!  I’ll update in a bit and respond back with any more questions I have.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sixem** [comment]
I should also mention that you should probably just remove all of the previous files if you are upgrading as the structure of everything has changed quite a bit since that version.

**Comment by soarn** [comment]
All good, I updated from 1.0.4 to 1.1.5, no problems so far.  Just some questions though:
1) Will you bring back the wget download info box?
2) How are themes used? (#10 )
3) Can the date be changed? (#11 )
4) I can't seem to get the filter to work:
```php
'filter' => array(
        'file' => false,
        'directory' => 'directory-i-dont-want-to-appear`, `dont-show-this-directory-either`
    ),
```
Is this setup correctly or am I doing something wrong?
Thanks in advance!

**Comment by sixem** [comment]
The filter uses regular expressions so it can be a little bit confusing 😅 

I'm no expert at regex but doing something like this `'directory' => '/^(?:(?!\b(hidethis|andthis|andthisaswell)\b).)*$/'` should hide all of those folders. Basically, the name needs to pass the regex, and in this case the regex checks for anything **not** matching those strings.

**Comment by soarn** [comment]
Ah, thank you!

**Comment by soarn** [comment]
That fixed it!  Thank you!  One last question, is there a way to make everything more centered in the middle of the screen like the old version was?  Other than that, its perfect!

**Comment by sixem** [comment]
No problem.

There is currently no setting to make things more centered. I changed the layout because i wanted to get more usage out of the screen space, but what you could do is just change the spreadsheet yourself.

Maybe adding something like this to the bottom of `style.css`?

```
@media only screen and (min-width: 640px)
{
  body
  {
    min-width: 640px;
    width: auto;
    max-width: 960px;
    margin: 0 auto;

    border: 1px solid var(--color-border-main);
  }
}
```

It would probably need a few adjustments though, but something like that should work.
